name: "My First Github Action" # 깃허브 액션의 이름

on: push # 트리거 이벤트를 정의. 푸쉬했을 때 작동한다! 여러개를 선언할 수도 있다.

env: # 환경 변수 지정. 각 환경 변수는 자신의 블록(인덴테이션)에 해당하는 스코프를 가짐. 스코프는 최소한으로 유지하는 것이 좋다.
  WORKFLOW_LEVEL: 'This value comes from the workflow level'

jobs: # 어떤 일을 할지를 정의
  first-job: # 빌드 서버 하나. 독립적인 머신 여러개가 있을 때는 누가 먼저 실행될지 알 수 없음.(병렬)
    name: 'First Job'

    strategy:
      matrix: 
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
    runs-on: ${{ matrix.os }} # 빌드 서버의 운영체제를 정의. 이것도 여러개를 선언할 수도 있음.

    steps: # 어떤 스텝으로 실행할 것인가를 정의
    - name: 'Say Hello on ${{ matrix.os }}'
      shell: bash
      run: | # 멀티 라인 명령을 넣을 때는 | 을 넣어야함.
        echo "Hello from ${{ matrix.os }}"